2025 09 2312 09
Tags: #mongoose 
###### Links: 
1) 
# Заметка
Принято обрабатывать ошибки централизованно, а не в блоке try catch всех функций. Для этого потребуется:
1) Добавить специальный мидлвар-обработчик
2) Пробросить ошибки контроллера в него
3) Описать собственные классы ошибок, внутри которых мы определим HTTP-статус ответа.
## Добавление мидлвара обработчика ошибок
В Express для обработки ошибок используется специальный обработчик:
```ts
app.use((err, req, res, next) => {
  // это обработчик ошибки
});
```
Он отличается от обработчика запроса тем, что принимает не 3, а 4 параметра. Первый дополнительный параметр содержит объект ошибки.
Чтобы обработчик сработал корректно, его необходимо определить последним, после всех `app.use`. Обычно это делают где-то в конце файла `app.ts`:
```ts
// app.ts

// весь код app.ts

// здесь обрабатываем все ошибки
app.use((err, req, res, next) => {
  res.status(500).send({ message: 'На сервере произошла ошибка' });
});

app.listen(PORT);
```
## Пробрасывание ошибок в мидлвар
Для того, чтобы пробросить в обработчик ошибок, нужно передать в next какой-либо аргумент, чаще всего это экземпляр ошибки. Чтобы выставить статус-код ответа для ошибки - это передать дополнительное свойство и вызвать next
```ts
try {
  payload = jwt.verify(token, 'some-secret-key');
} catch (e) {
  const err = new Error('Необходима авторизация'); 
  err.statusCode = 401;

  next(err);
}
```
Для ошибок, которые часто повторяются, удобно использовать свои конструкторы. Простейший конструктор 404 ошибки будет выглядеть так
```ts
// errors/not-found-err.js

class NotFoundError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 404;
  }
}

module.exports = NotFoundError;
```
Всё, что делает этот конструктор, — наследует от стандартной ошибки и выставляет свойство `statusCode`. После создания конструктора `NotFoundError`, его можно импортировать в другие места кода и использовать вместе с инструкцией `throw`:
```ts
const NotFoundError = require('./errors/not-found-err');

module.exports.getProfile = (req, res, next) => User
  .findOne({ _id: req.params.userId })
  .then((user) => {
    if (!user) {
      // если такого пользователя нет,
      // сгенерируем исключение
      throw new NotFoundError('Нет пользователя с таким id');
    }

    res.send(user);
  })
  // ...
```
Ели ошибка была сгенерирована не нами, у нее не будет статуса ошибки. В этом случае будем считать произошедшее ошибкой сервера, возвращать 500 статус и стандартное сообщение: